# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: example-app
  name: example-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: example-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: example-app
    spec:
      containers:
        - image: php:7-apache
          imagePullPolicy: Always
          name: example-app
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: "index-php"
              mountPath: "/var/www/html/"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
      terminationGracePeriodSeconds: 10
      volumes:
        - name: "index-php"
          configMap:
            name: "example-app"
            items:
              - key: "index.php"
                path: "index.php"

